from pathlib import Path

import pandas as pd


BASE_DIR = Path(__file__).resolve().parents[1]
DATA_DIR = BASE_DIR / "data"
OUTPUT_FILE = DATA_DIR / "sales_dirty_week3.csv"

DATA_DIR.mkdir(exist_ok=True)


sales_data = [
    {
        "order_id": "O1001",
        "order_date": "2026-01-03",
        "city": "上海",
        "channel": "天猫",
        "product_name": "无线鼠标",
        "category": "电脑配件",
        "quantity": "3",
        "unit_price": "129",
        "discount_rate": "10%",
        "order_status": "已完成",
    },
    {
        "order_id": "O1002",
        "order_date": "2026/01/05",
        "city": "北京 ",
        "channel": "京东",
        "product_name": "机械键盘",
        "category": "电脑配件",
        "quantity": "2",
        "unit_price": "399",
        "discount_rate": "0.05",
        "order_status": "已完成",
    },
    {
        "order_id": "O1003",
        "order_date": "2026年01月08日",
        "city": "广州",
        "channel": "抖音",
        "product_name": "蓝牙耳机",
        "category": "数码产品",
        "quantity": "5",
        "unit_price": "199",
        "discount_rate": "无折扣",
        "order_status": "已完成",
    },
    {
        "order_id": "O1004",
        "order_date": "2026-01-15",
        "city": "深圳",
        "channel": "天猫 ",
        "product_name": "无线鼠标",
        "category": "电脑配件",
        "quantity": "4件",
        "unit_price": "129",
        "discount_rate": "10%",
        "order_status": "已完成",
    },
    {
        "order_id": "O1005",
        "order_date": "2026-01-20",
        "city": "上海",
        "channel": "京东",
        "product_name": "移动硬盘",
        "category": "数码产品",
        "quantity": "1",
        "unit_price": "599元",
        "discount_rate": "0",
        "order_status": "已取消",
    },
    {
        "order_id": "O1006",
        "order_date": "2026-01-32",
        "city": "北京",
        "channel": "抖音",
        "product_name": "蓝牙耳机",
        "category": "数码产品",
        "quantity": "3",
        "unit_price": "199",
        "discount_rate": "5%",
        "order_status": "已完成",
    },
    {
        "order_id": "O1007",
        "order_date": "2026-02-02",
        "city": "广州",
        "channel": "天猫",
        "product_name": "机械键盘",
        "category": "电脑配件",
        "quantity": "3",
        "unit_price": "399",
        "discount_rate": "15%",
        "order_status": "已完成",
    },
    {
        "order_id": "O1008",
        "order_date": "2026-02-06",
        "city": "深圳",
        "channel": "京东",
        "product_name": "无线鼠标",
        "category": "电脑配件",
        "quantity": "6",
        "unit_price": "129",
        "discount_rate": "0.1",
        "order_status": "已完成",
    },
    {
        "order_id": "O1008",
        "order_date": "2026-02-06",
        "city": "深圳",
        "channel": "京东",
        "product_name": "无线鼠标",
        "category": "电脑配件",
        "quantity": "6",
        "unit_price": "129",
        "discount_rate": "0.1",
        "order_status": "已完成",
    },
    {
        "order_id": "O1009",
        "order_date": "2026.02.10",
        "city": "上海 ",
        "channel": "抖音",
        "product_name": "蓝牙耳机",
        "category": "数码产品",
        "quantity": "缺货",
        "unit_price": "199",
        "discount_rate": "5%",
        "order_status": "已取消",
    },
    {
        "order_id": "O1010",
        "order_date": "2026-02-14",
        "city": "北京",
        "channel": "天猫",
        "product_name": "移动硬盘",
        "category": "数码产品",
        "quantity": "2",
        "unit_price": "599",
        "discount_rate": "",
        "order_status": "已完成",
    },
    {
        "order_id": "O1011",
        "order_date": "2026-02-18",
        "city": "广州",
        "channel": "京东",
        "product_name": "机械键盘",
        "category": "电脑配件",
        "quantity": "4",
        "unit_price": "价格待定",
        "discount_rate": "10%",
        "order_status": "已完成",
    },
    {
        "order_id": "O1012",
        "order_date": "",
        "city": "深圳",
        "channel": "抖音",
        "product_name": "蓝牙耳机",
        "category": "数码产品",
        "quantity": "7",
        "unit_price": "199",
        "discount_rate": "20%",
        "order_status": "已完成",
    },
    {
        "order_id": "O1013",
        "order_date": "2026-03-01",
        "city": "上海",
        "channel": "天猫",
        "product_name": "无线鼠标",
        "category": "电脑配件",
        "quantity": "8",
        "unit_price": "129",
        "discount_rate": "10%",
        "order_status": "已完成",
    },
    {
        "order_id": "O1014",
        "order_date": "2026/03/05",
        "city": "北京",
        "channel": "京东",
        "product_name": "机械键盘",
        "category": "电脑配件",
        "quantity": "3",
        "unit_price": "399",
        "discount_rate": "5%",
        "order_status": "已完成",
    },
    {
        "order_id": "O1015",
        "order_date": "2026-03-09",
        "city": "广州 ",
        "channel": "抖音",
        "product_name": "蓝牙耳机",
        "category": "数码产品",
        "quantity": "9",
        "unit_price": "199",
        "discount_rate": "0.15",
        "order_status": "已完成",
    },
    {
        "order_id": "O1016",
        "order_date": "2026-03-12",
        "city": "深圳",
        "channel": "天猫",
        "product_name": "移动硬盘",
        "category": "数码产品",
        "quantity": "2",
        "unit_price": "599",
        "discount_rate": "10%",
        "order_status": "已完成",
    },
    {
        "order_id": "O1017",
        "order_date": "not_a_date",
        "city": "上海",
        "channel": "京东",
        "product_name": "无线鼠标",
        "category": "电脑配件",
        "quantity": "5",
        "unit_price": "129",
        "discount_rate": "5%",
        "order_status": "已完成",
    },
    {
        "order_id": "O1018",
        "order_date": "2026-03-20",
        "city": "北京",
        "channel": "抖音",
        "product_name": "蓝牙耳机",
        "category": "数码产品",
        "quantity": "",
        "unit_price": "199",
        "discount_rate": "10%",
        "order_status": "已取消",
    },
    {
        "order_id": "O1019",
        "order_date": "2026-03-25",
        "city": "",
        "channel": "天猫",
        "product_name": "机械键盘",
        "category": "电脑配件",
        "quantity": "5",
        "unit_price": "399",
        "discount_rate": "10%",
        "order_status": "已完成",
    },
]


df = pd.DataFrame(sales_data)

df.to_csv(
    OUTPUT_FILE,
    index=False,
    encoding="utf-8-sig",
)

print("销售脏数据已生成：")
print(OUTPUT_FILE)
print("数据行数：", len(df))
print("数据列数：", len(df.columns))
print(df.head())